---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features, administration, amazon fsx for netapp ontap, databases, genai, vmware' 
summary: Obtenga información sobre los cambios más recientes en las cargas de trabajo que forman parte de NetApp Workload Factory. 
---
= Cambios recientes en NetApp Workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Obtenga información sobre los cambios más recientes en las cargas de trabajo que forman parte de NetApp Workload Factory.



== 01 de febrero de 2026



=== Cargas de trabajo de



==== Análisis bien arquitectado para Amazon Elastic VMware Service

Workload Factory ahora ofrece análisis automatizados bien diseñados para tus entornos de Amazon Elastic VMware Service (EVS). Los análisis diarios identifican desajustes de configuración y ofrecen recomendaciones detalladas de corrección para ayudarte a mantener operaciones, seguridad y eficiencia de costos óptimas.

Los análisis se realizan mediante las API de AWS—no se requieren credenciales de vSphere ni conectividad a vCenter. Los resultados están disponibles en la nueva pestaña *Well-architected status* dentro de los detalles de tu entorno EVS.

Esta versión incluye información para:

* *Estado de la protección de parada/terminación de la instancia*: Identifica los nodos EVS sin protección de parada o terminación de EC2. Detener o terminar nodos EVS desde la consola EC2 puede provocar la indisponibilidad de datos de máquinas virtuales o la pérdida de datos.
* *Alineación de la ubicación de la partición del nodo del clúster*: detecta desalineaciones de particiones que podrían provocar una pérdida significativa de potencia de procesamiento o tiempo de inactividad si falla una partición dentro de una AWS Availability Zone. Cada insight incluye niveles de gravedad, hallazgos detallados con información sobre los recursos afectados y procedimientos de remediación paso a paso basados en las mejores prácticas de AWS.


link:view-evs-well-architected.html["Implementa configuraciones bien diseñadas"]



=== Configuración y administración



==== Actualizaciones bien arquitectadas

NetApp Workload Factory incluye la evaluación bien diseñada para cargas de trabajo de Elastic VMware Service (EVS), y añade nuevas configuraciones para cargas de trabajo de Storage y Database.

* *Cargas de trabajo de VMware* NetApp Workload Factory proporciona las mejores prácticas y recomendaciones para operar cargas de trabajo de Amazon Elastic VMware Service (EVS) bien arquitectadas.
+
link:https://docs.netapp.com/us-en/workload-vmware/view-evs-well-architected.html["Implementa configuraciones de EVS bien diseñadas"^]

* *Cargas de trabajo de almacenamiento* Se han añadido varias configuraciones nuevas a la función well-architected en la carga de trabajo de almacenamiento para que tengas más información sobre el rendimiento y los costos del almacenamiento.
+
** Informes lógicos de Storage VM
** Optimiza el tamaño del volumen de caché
** Dispositivos de bloque huérfanos
+
link:https://docs.netapp.com/us-en/workload-fsx-ontap/improve-configurations.html["Implementa configuraciones de sistemas de archivos bien diseñadas para cargas de trabajo de almacenamiento"^]



* *Cargas de trabajo de bases de datos* Workload Factory for Databases incluye una nueva configuración de almacenamiento para Oracle para habilitar y configurar Direct NFS (dNFS) para mejorar el rendimiento de I/O y disminuir la carga en el host y el sistema de almacenamiento.
+
** habilitación de dNFS
** resolución IP coherente de dNFS
** dNFS archivo de configuración
** dNFS `nosharecache`
+
link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["Implementar cargas de trabajo de bases de datos bien diseñadas"^]







==== Nuevos permisos para Storage

Se han añadido nuevos permisos a la carga de trabajo de Storage para mejoras en la gestión de los puntos de acceso S3.

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html#change-log["Registro de cambios de referencia de permisos"]



=== Cargas de trabajo de los constructores



==== Filtrado mejorado del panel de control con etiquetas personalizables

Ahora puedes configurar hasta cinco filtros personalizados en el panel de EDA según tus etiquetas de AWS. Cada filtro personalizado incluye un nombre de etiqueta, una clave de etiqueta de AWS y un tipo de selección (selección única o múltiple).

La selección múltiple te permite seleccionar varios valores simultáneamente, mientras que la selección única te restringe a un valor a la vez. Los filtros personalizados aparecen en el orden en que los configuras, lo que hace que sea fácil organizar los filtros que usas con más frecuencia.

Si no configuras filtros personalizados, los filtros predeterminados (sistema de archivos, tipo de volumen e intervalo de tiempo) siguen disponibles para que puedas seguir viendo e interactuando con tus cuadros de mando.

https://docs.netapp.com/us-en/workload-eda/task-configure-dashboard.html["Aprende más sobre cómo configurar filtros personalizados"^].



==== Vista de detalles del volumen para un análisis granular del rendimiento

El panel ahora ofrece dos modos de visualización: vista total y vista por volumen. La vista total muestra las métricas agregadas de todos los volúmenes, mientras que la vista por volumen muestra el rendimiento individual de los 10 volúmenes principales a lo largo del tiempo.

En la vista Volumen, las descripciones emergentes interactivas al pasar el cursor ofrecen información detallada para cada volumen, incluyendo el nombre del volumen, las métricas y los valores específicos según el tiempo. Cuando los mismos volúmenes aparecen en varios componentes, un código de colores coherente hace que sea más fácil seguir volúmenes específicos en diferentes métricas.

https://docs.netapp.com/us-en/workload-eda/task-configure-dashboard.html#view-volume-details["Obtén más información sobre cómo ver los detalles del volumen"^].



==== Análisis de latencia para la supervisión proactiva del rendimiento

El análisis de latencia te permite supervisar la latencia de lectura y escritura de volúmenes en tus sistemas de archivos FSx para ONTAP. Puedes configurar umbrales de advertencia y de eventos críticos personalizables para identificar de forma proactiva cuellos de botella en el rendimiento antes de que afecten tus cargas de trabajo EDA.

La tabla de eventos de latencia muestra todos los eventos de advertencia y críticos que te permiten supervisar el rendimiento del volumen e identificar los volúmenes que requieren optimización.

Esta función requiere credenciales de AWS y es accesible desde el menú Latencia en el panel de EDA.

https://docs.netapp.com/us-en/workload-eda/task-monitor-latency.html["Conoce más sobre el análisis de latencia"^].



== 04 de enero de 2026



=== Amazon FSX para ONTAP de NetApp



==== Actualizaciones de análisis bien diseñadas

Workload Factory analiza sus sistemas de archivos FSx for ONTAP para las siguientes configuraciones:

* La protección autónoma contra ransomware de NetApp (ARP/AI) deshabilitada incluye dispositivos de bloque: comprueba si ARP/AI está deshabilitado en los volúmenes de dispositivos de bloque
* Modo de escritura de la relación de caché: verifica si el modo de escritura es óptimo para la carga de trabajo del volumen de caché
* Eliminación de copias de seguridad innecesarias: comprueba si las copias de seguridad están desactualizadas o son innecesarias y se pueden eliminar para reducir costes


link:https://docs.netapp.com/us-en/workload-fsx-ontap/improve-configurations.html["Visualice el estado de buena arquitectura de sus sistemas de archivos FSx para ONTAP"]



==== Integración de la página de inicio del asistente de IA de Ask Me

La página de inicio de la consola Workload Factory incorpora el asistente de IA Ask me, que le permite hacer preguntas sobre su propio almacenamiento, obtener información personalizada directamente de su entorno y consultar conversaciones anteriores. Puede interactuar con Pregúnteme para comprender sus cargas de trabajo, solucionar problemas y obtener más información sobre Workload Factory, todo sin salir de la consola.



==== Uso del principal de usuario de IAM en políticas de permisos basadas en recursos de enlaces Lambda

Los enlaces Lambda que se utilizan para conectar su cuenta de Workload Factory y uno o más sistemas de archivos FSx for ONTAP para realizar operaciones ONTAP avanzadas, ahora usan el principal de usuario de IAM para permisos de políticas basadas en recursos. Este cambio proporciona una mejor alineación con las mejores prácticas de la industria para el acceso a los recursos de AWS.



==== Se agregó una pantalla de análisis para el analizador de IA para eventos EMS

Se ha agregado una nueva pantalla _Análisis_ al menú Almacenamiento. Desde esta pantalla, puede utilizar la función de analizador de IA para eventos EMS de FSx para ONTAP .



==== Mejoras en los dispositivos de bloque en NetApp Workload Factory

Se han realizado las siguientes mejoras para los dispositivos de bloque.



===== Creación de dispositivos de bloque

NetApp Workload Factory admite la creación de dispositivos de bloque mediante el protocolo iSCSI en FSx para sistemas de archivos ONTAP para que pueda brindar un mejor soporte a sus aplicaciones de línea de negocio (LOB) desde la consola de Workload Factory.



===== Mejoras en la gestión de dispositivos de bloque

NetApp Workload Factory incluye las siguientes mejoras para link:https://docs.netapp.com/us-en/workload-fsx-ontap/manage-block-devices.html["gestión de dispositivos de bloque"]. Ahora puede realizar las siguientes tareas desde la consola de Workload Factory:

* Administrar el acceso de los clientes
* Archivar datos del dispositivo de bloque
* Eliminar un dispositivo de bloque




===== Compatibilidad con ARP/AI en volúmenes FlexVol que contienen dispositivos de bloque

Puedes habilitar link:https://docs.netapp.com/us-en/workload-fsx-ontap/ransomware-protection.html["Protección autónoma contra ransomware de NetApp con IA (ARP/AI)"] en volúmenes FlexVol que contienen dispositivos de bloque. La habilitación de ARP/AI detecta ataques de ransomware mediante IA y ayuda en la recuperación de datos.



=== Cargas de trabajo de base de datos



==== Integración de la página de inicio del asistente de IA de Ask Me

La página de inicio de la consola Workload Factory incorpora el asistente de IA Ask me, que le permite hacer preguntas sobre su propio almacenamiento, obtener información personalizada directamente de su entorno y consultar conversaciones anteriores. Puede interactuar con Pregúnteme para comprender sus cargas de trabajo, solucionar problemas y obtener más información sobre Workload Factory, todo sin salir de la consola.



=== Cargas de trabajo de



==== Integración de la página de inicio del asistente de IA de Ask Me

La página de inicio de la consola Workload Factory incorpora el asistente de IA Ask me, que le permite hacer preguntas sobre su propio almacenamiento, obtener información personalizada directamente de su entorno y consultar conversaciones anteriores. Puede interactuar con Pregúnteme para comprender sus cargas de trabajo, solucionar problemas y obtener más información sobre Workload Factory, todo sin salir de la consola.



=== Configuración y administración



==== Integración de la página de inicio del asistente de IA de Ask Me

La página de inicio de la consola Workload Factory incorpora el asistente de IA Ask me, que le permite hacer preguntas sobre su propio almacenamiento, obtener información personalizada directamente de su entorno y consultar conversaciones anteriores. Puede interactuar con Pregúnteme para comprender sus cargas de trabajo, solucionar problemas y obtener más información sobre Workload Factory, todo sin salir de la consola.



=== Cargas de trabajo de los constructores



==== NetApp Workload Factory para desarrolladores ahora NetApp Workload Factory para EDA

Workload Factory para constructores ahora es Workload Factory para EDA. El cambio de nombre refleja el enfoque en las cargas de trabajo de automatización de diseño electrónico (EDA).

Workload Factory para EDA le ayuda a optimizar FSx para ONTAP en múltiples sistemas de archivos. Puede optimizar el rendimiento y reducir los costos operativos automatizando los parámetros de almacenamiento, analizando las restricciones de rendimiento y obteniendo información sobre los proyectos de EDA. Workload Factory para EDA está diseñado para integrarse con sus marcos de infraestructura como código (IaC).



==== Integración de la página de inicio del asistente de IA de Ask Me

La página de inicio de la consola Workload Factory incorpora el asistente de IA Ask me, que le permite hacer preguntas sobre su propio almacenamiento, obtener información personalizada directamente de su entorno y consultar conversaciones anteriores. Puede interactuar con Pregúnteme para comprender sus cargas de trabajo, solucionar problemas y obtener más información sobre Workload Factory, todo sin salir de la consola.



== 18 de diciembre de 2025



=== Cargas de trabajo de base de datos



==== Mejoras en la integración de Active Directory

Workload Factory for Databases incluye tres nuevos campos de Active Directory (AD) al implementar Microsoft SQL Server mediante la opción *Creación avanzada*. Estas mejoras le permiten especificar las preferencias de unión de Active Directory y utilizar una cuenta de servicio administrada.

Los nuevos campos de AD son:

* Controlador de dominio preferido
* Ruta de unidad organizativa preferida
* Grupo de Active Directory de destino


link:https://docs.netapp.com/us-en/workload-databases/create-database.html["Implementar Microsoft SQL Server"]



== 04 de diciembre de 2025



=== Amazon FSX para ONTAP de NetApp



==== Compatibilidad con puntos de acceso AWS S3 para FSx para ONTAP

NetApp Workload Factory admite puntos de acceso AWS S3 para sus sistemas de archivos FSx para ONTAP . Puede crear volúmenes utilizando puntos de acceso S3, asignar puntos de acceso S3 a un volumen existente y administrar puntos de acceso S3 desde la consola de Workload Factory. Al utilizar un punto de acceso S3, puede acceder a los datos de archivos que residen en volúmenes SMB/CIFS o NFS a través de las API de AWS S3. Esto le permite integrar sus datos existentes con GenAI, ML y análisis de los servicios de AWS que admiten puntos de acceso S3.

* link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-volume.html["Crear un volumen utilizando puntos de acceso S3"]
* link:https://docs.netapp.com/us-en/workload-fsx-ontap/manage-s3-access-points.html["Administrar puntos de acceso S3 para un volumen"]




== 27 de noviembre de 2025



=== Amazon FSX para ONTAP de NetApp



==== Compatibilidad con dispositivos de bloque en NetApp Workload Factory

Administre sus dispositivos de bloque de manera más efectiva con la compatibilidad con dispositivos de bloque recientemente introducida en NetApp Workload Factory. Esta función le permite ver detalles y aumentar la capacidad de los LUN iSCSI, lo que proporciona una mayor flexibilidad para sus necesidades de almacenamiento.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/manage-block-devices.html["Administrar dispositivos de bloque en Workload Factory"]



==== Actualizaciones de análisis bien diseñadas

Workload Factory analiza sus sistemas de archivos FSx para ONTAP para las siguientes configuraciones:

* Eliminación de instantáneas innecesarias: verifica si los volúmenes tienen instantáneas obsoletas e innecesarias que se puedan eliminar para reducir costos.
* Reequilibrio de volúmenes FlexGroup : verifica si los volúmenes FlexGroup están equilibrados de manera uniforme entre sus volúmenes miembros para garantizar un rendimiento óptimo.


link:https://docs.netapp.com/us-en/workload-fsx-ontap/improve-configurations.html["Visualice el estado de buena arquitectura de sus sistemas de archivos FSx para ONTAP"]



==== Analizador de IA para eventos EMS en NetApp Workload Factory

NetApp Workload Factory presenta un analizador impulsado por IA para eventos del sistema de gestión de eventos (EMS) de ONTAP . Esta función le ayuda a identificar y solucionar problemas rápidamente al proporcionar información y recomendaciones basadas en el análisis de datos de eventos de EMS.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/analyze-events.html["Analizar eventos EMS en Workload Factory"]



==== Supervisar las tendencias de costos y uso de los sistemas de archivos FSx para ONTAP

Puede monitorear las tendencias de costos y uso de sus sistemas de archivos FSx for ONTAP directamente desde la consola de NetApp Workload Factory . Esta función proporciona métricas de consumo y costos de almacenamiento, así como costos detallados, lo que le ayuda a optimizar la asignación de recursos y la planificación del presupuesto.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/track-costs.html["Seguimiento de costos de FSx para sistemas de archivos ONTAP en Workload Factory"]



==== Administrar etiquetas FSx para un sistema de archivos en NetApp Workload Factory

Administre fácilmente sus etiquetas FSx para un sistema de archivos directamente desde la consola de NetApp Workload Factory . Esta función le permite agregar, editar o eliminar etiquetas, lo que permite una mejor organización y categorización de sus sistemas de archivos FSx para ONTAP .

link:https://docs.netapp.com/us-en/workload-fsx-ontap/manage-fsx-tags.html["Administrar etiquetas FSx en Workload Factory"]



==== Ajustar la capacidad de caché para FSx para sistemas de archivos ONTAP

Puede aumentar y disminuir la capacidad de los volúmenes de caché desde la consola de Workload Factory.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/manage-cache-volumes.html["Administrar volúmenes de caché en Workload Factory"]



=== Cargas de trabajo de base de datos



==== Optimice los ahorros en la calculadora de bases de datos para Amazon Elastic Block Store (EBS)

Dos nuevas funciones de la calculadora mejoran el análisis de ahorro de costos al ejecutar múltiples instancias con almacenamiento EBS para que pueda ahorrar más al cambiar a FSx para ONTAP.

* Workload Factory proporciona una solución de almacenamiento consolidada para varios hosts de bases de datos en un sistema de archivos FSx para ONTAP . Esta consolidación optimiza los costos de almacenamiento al reducir la cantidad de sistemas de archivos necesarios para múltiples hosts de bases de datos, lo que genera mayores ahorros de costos.
* Workload Factory analiza el uso del rendimiento de EBS y luego sugiere la mejor y más rentable configuración de FSx para ONTAP .


link:https://docs.netapp.com/us-en/workload-databases/explore-savings.html#explore-savings-for-detected-hosts["Explora los ahorros para los hosts EBS detectados"]



==== Informe de Excel disponible para el panel de control bien diseñado

Puede descargar un informe de Excel del panel de control bien diseñado. El informe proporciona el estado bien diseñado del recurso de base de datos y recomendaciones para todas las configuraciones de recursos, incluidas las subconfiguraciones para el sistema operativo y ONTAP.



==== Analizador de registro de errores disponible para bases de datos Oracle

El analizador de registros de errores impulsado por IA de Agentic está disponible para bases de datos Oracle. La función aprovecha algoritmos avanzados de aprendizaje automático para detectar y analizar automáticamente errores en los archivos de registro. Esta herramienta tiene como objetivo agilizar el proceso de resolución de problemas al proporcionar a los desarrolladores información práctica y recomendaciones basadas en los patrones que identifica en los registros.

link:https://docs.netapp.com/us-en/workload-databases/analyze-error-logs.html["Obtenga más información sobre el analizador de registros de errores impulsado por IA de Agentic"]



==== Análisis bien diseñado para Oracle

El análisis bien diseñado incluye dos nuevas configuraciones de tamaño de almacenamiento. El análisis evalúa y corrige problemas de configuración relacionados con la asignación de espacio de intercambio y el margen del sistema de archivos para implementaciones de bases de datos Oracle existentes.

link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["Implementar configuraciones de base de datos bien diseñadas en Workload Factory"]



=== Cargas de trabajo de



==== Calcule el ahorro de costos al migrar a Amazon Elastic VMware Service para regiones específicas

Ahora puede explorar el valor de diferentes opciones de implementación para su migración a la nube, optimizar los esfuerzos invertidos en la evaluación de soluciones y profundizar en soluciones que tienen el potencial de ofrecer valor y ahorros en la nube.

También puede revisar los ahorros en núcleos de vCPU que se pueden lograr al usar FSx para ONTAP para una implementación de EVS.

https://docs.netapp.com/us-en/workload-vmware/calculate-evs-savings.html["Explore los ahorros de Amazon Elastic VMware Service con NetApp Workload Factory"]



=== Configuración y administración



==== Actualización de permisos para almacenamiento

El analizador de eventos de FSx para ONTAP EMS utiliza los siguientes permisos de Amazon Bedrock en la política de permisos _operaciones y remediación_ para obtener datos de eventos para la carga de trabajo de almacenamiento.

* `bedrock:ListInferenceProfiles`
* `bedrock:GetInferenceProfile`
* `bedrock:InvokeModelWithResponseStream`
* `bedrock:InvokeModel`


link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html#change-log["Registro de cambios de referencia de permisos"]
