---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features, administration, amazon fsx for netapp ontap, databases, genai, vmware' 
summary: Obtenga información sobre los cambios más recientes en las cargas de trabajo que forman parte de NetApp Workload Factory. 
---
= Cambios recientes en NetApp Workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Obtenga información sobre los cambios más recientes en las cargas de trabajo que forman parte de NetApp Workload Factory.



== 02 de marzo de 2026



=== Cargas de trabajo de base de datos



==== Evaluación única

Workload Factory ahora ofrece una evaluación única para analizar las configuraciones de tus implementaciones de bases de datos cuando lo necesites: nuevas implementaciones, posmigración, solución de problemas y más. Recibirás recomendaciones para ayudarte a optimizar las configuraciones de tus implementaciones y cumplir con las mejores prácticas. Esta es tu oportunidad de usar la función well-architected sin comprometerte completamente con el proceso de configuración. Puedes evaluar tus bases de datos sin guardar credenciales en Workload Factory, registrar recursos de bases de datos ni configurar conexiones externas.

link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["Realiza una evaluación única de tus implementaciones de bases de datos"]



==== Soporte de registro para Always On availability groups en Microsoft SQL Server y Data Guard en Oracle

Ahora puedes descubrir y registrar instancias de Microsoft SQL Server con el modelo de implementación Always On availability group (AOAG) y bases de datos Oracle con el modelo de implementación Data Guard en la carga de trabajo de bases de datos de NetApp Workload Factory. Esta mejora permite una mejor gestión de los recursos de SQL Server y Oracle dentro de la consola de Workload Factory.

Después de registrar tus instancias de AOAG y bases de datos de Data Guard, puedes aprovechar las diversas funciones de Workload Factory for Databases, como ver detalles de recursos y analizar registros de errores.

Workload Factory for Databases también es compatible con el análisis bien diseñado para instancias de Microsoft SQL Server con el modelo de despliegue AOAG. Puedes analizar las configuraciones de tus instancias de SQL Server en un grupo de disponibilidad y recibir recomendaciones para optimizar tus configuraciones de despliegue y cumplir con las mejores prácticas. Registra tus instancias AOAG para habilitar esta función.

link:https://docs.netapp.com/us-en/workload-databases/register-instance.html#register-a-sql-server-instance["Registrar recursos en Workload Factory para bases de datos"]



==== Análisis bien diseñado para Oracle

El análisis bien diseñado incluye *Parches del sistema operativo* para que Oracle compruebe si tienes los últimos parches en el sistema operativo y te diga cómo instalarlos.

Además, el análisis bien diseñado para Oracle te notifica cuando una configuración como la distribución de almacenamiento tiene dependencias con otras configuraciones. La notificación te dice qué acciones optimizar en las configuraciones vinculadas para que todas las recomendaciones que te damos sean óptimas.

link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["Implementar configuraciones de base de datos bien diseñadas en Workload Factory"]



==== Análisis de costes y planificación de la migración en entornos de bases de datos Oracle locales

Workload Factory for Databases ahora analiza y te ayuda a planificar la migración de bases de datos locales de Oracle a Amazon FSx for NetApp ONTAP. Puedes usar la calculadora de ahorro para estimar el costo de ejecutar tu entorno de bases de datos locales de Oracle en la nube y revisar recomendaciones para migrar tu entorno de bases de datos locales a la nube.

link:https://docs.netapp.com/us-en/workload-databases/explore-savings.html["Explora ahorros para entornos de bases de datos locales"]



==== Nuevo marcador Ask Me disponible en Workload Factory

Hemos añadido un nuevo marcador Ask Me en cada pantalla de la consola Workload Factory. Esta mejora hace que sea más fácil y rápido para ti acceder a Ask Me siempre que necesites ayuda. Ask Me es nuestro asistente de IA, que te permite hacer preguntas sobre tus propios entornos de carga de trabajo, obtener información personalizada directamente de tu entorno y consultar conversaciones anteriores.

Puedes abrir Ask Me desde cualquier página haciendo clic en el nuevo marcador. Lanza Ask Me en un panel lateral sin interrumpir tu trabajo actual y ofrece explicaciones y recomendaciones rápidas relacionadas con lo que estás haciendo en ese momento.

link:https://docs.netapp.com/us-en/workload-setup-admin/workload-factory-overview.html#features["Conoce más sobre Ask Me"^]



== 01 de marzo de 2026



=== Configuración y administración



==== Nuevo marcador Ask Me disponible en Workload Factory

Hemos añadido un nuevo marcador Ask Me en cada pantalla de la consola Workload Factory. Esta mejora hace que sea más fácil y rápido para ti acceder a Ask Me siempre que necesites ayuda. Ask Me es nuestro asistente de IA, que te permite hacer preguntas sobre tus propios entornos de carga de trabajo, obtener información personalizada directamente de tu entorno y consultar conversaciones anteriores.

Puedes abrir Ask Me desde cualquier página haciendo clic en el nuevo marcador. Lanza Ask Me en un panel lateral sin interrumpir tu trabajo actual y ofrece explicaciones y recomendaciones rápidas relacionadas con lo que estás haciendo.

link:https://docs.netapp.com/us-en/workload-setup-admin/workload-factory-overview.html#features["Conoce más sobre Ask Me"]



=== Cargas de trabajo EDA



==== Panel de control general para la gestión del almacenamiento EDA

Como administrador de TI que gestiona docenas de sistemas de archivos FSx for ONTAP, puedes usar el panel de información general para responder preguntas operativas comunes sobre la salud del clúster, la utilización y la colocación de volúmenes.

El panel de resumen incluye:

* *Estado de salud del clúster*: Información resumida en la parte superior del panel de control que destaca el rendimiento, la capacidad, la disponibilidad, la protección y los eventos de seguridad en todos tus clústeres.
* *Tabla de clústeres*: Una tabla con búsqueda, filtrado y paginación que muestra la capacidad SSD, el grupo de capacidad y las métricas de rendimiento por clúster, con soporte para la personalización de columnas y exportación CSV.


El anterior cuadro de mandos principal ahora es accesible en la pestaña *Project*. Las pestañas EDA ahora están ordenadas: visión general, latencia, Project, CI/CD.

https://docs.netapp.com/us-en/workload-eda/task-use-overview-dashboard.html["Conoce más sobre el panel de resumen"^].



==== Análisis automatizado de latencia

El análisis de latencia ahora incluye un análisis básico automatizado. Cuando se detectan eventos de latencia, el sistema analiza automáticamente las métricas de delay center de ONTAP QoS para identificar el origen de los problemas de latencia.

El análisis básico evalúa las políticas de QoS, el rendimiento de los discos, los problemas de red y las configuraciones de clúster para proporcionar información inmediata en la columna Details de la tabla de eventos de latencia.

https://docs.netapp.com/us-en/workload-eda/task-monitor-latency.html#understanding-basic-analysis["Aprende más sobre el análisis básico de latencia"^].



==== Nuevo marcador Ask Me disponible en Workload Factory

Hemos añadido un nuevo marcador Ask Me en cada pantalla de la consola Workload Factory. Esta mejora hace que sea más fácil y rápido para ti acceder a Ask Me siempre que necesites ayuda. Ask Me es nuestro asistente de IA, que te permite hacer preguntas sobre tus propios entornos de carga de trabajo, obtener información personalizada directamente de tu entorno y consultar conversaciones anteriores.

Puedes abrir Ask Me desde cualquier página haciendo clic en el nuevo marcador. Lanza Ask Me en un panel lateral sin interrumpir tu trabajo actual y ofrece explicaciones y recomendaciones rápidas relacionadas con lo que estás haciendo en ese momento.

link:https://docs.netapp.com/us-en/workload-setup-admin/workload-factory-overview.html#features["Conoce más sobre Ask Me"^]



== 16 febrero 2026



=== Amazon FSX para ONTAP de NetApp



==== Soporte para la migración de storage VM

NetApp Workload Factory ahora admite la migración para storage VMs. Esta función permite la migración de datos y configuraciones de sistemas de almacenamiento ONTAP desde sistemas ONTAP locales o sistemas de archivos FSx for ONTAP de primera generación a sistemas de archivos FSx for ONTAP de segunda generación. Puedes replicar datos y configuraciones de storage VM para trasladarlos al nuevo sistema de archivos con un tiempo de inactividad y una interrupción mínimos para los usuarios y las aplicaciones.

Para utilizar esta función, link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-replication.html["crear una relación de replicación"] y selecciona *Migration* como caso de uso. Para completar el proceso de migración, debes link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-replication.html#cut-over-replication-for-migration-use-cases["transiciona la máquina virtual de almacenamiento y sus volúmenes replicados"] inmediatamente para migrar de forma permanente los datos y la configuración de la VM de almacenamiento al sistema de archivos FSx for ONTAP de destino.



== 02 febrero 2026



=== Cargas de trabajo de base de datos



==== Ahorro de costes mejorado para varios hosts de bases de datos en Microsoft SQL Server on-premises

El análisis de ahorro de costes para el almacenamiento local de Microsoft SQL Server se ha mejorado para ofrecer una solución de almacenamiento consolidada para varios hosts de bases de datos en un solo sistema de archivos FSx para ONTAP. Esta consolidación optimiza los costes de almacenamiento al reducir el número de sistemas de archivos necesarios para varios hosts de bases de datos, lo que lleva a un mayor ahorro de costes.

link:https://docs.netapp.com/us-en/workload-databases/explore-savings.html#explore-savings-for-detected-hosts["Explora el ahorro para hosts detectados en Microsoft SQL Server on-premises"]



==== Análisis bien diseñado para Oracle

El análisis bien diseñado incluye cuatro nuevas subevaluaciones para el análisis de configuración de almacenamiento para Oracle: habilitación de dNFS, resolución IP coherente de dNFS, archivo de configuración de dNFS y dNFS `nosharecache`. Estas evaluaciones están relacionadas con la habilitación y configuración de Direct NFS (dNFS) para tu entorno Oracle, que omite el cliente de NFS del host y realiza operaciones de archivos NFS directamente en un servidor NFS, mejorando el rendimiento de I/O y disminuyendo la carga en el host y el sistema de almacenamiento porque la I/O se realiza de manera más eficiente.

link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["Implementar configuraciones de base de datos bien diseñadas en Workload Factory"]



== 01 de febrero de 2026



=== Amazon FSX para ONTAP de NetApp



==== La página de inicio incluye problemas bien diseñados y eventos EMS para Storage

La página de inicio de NetApp Workload Factory incluye un mosaico Focus donde aparecen las incidencias bien arquitecturadas y los eventos de FSx for ONTAP Emergency Management System (EMS) para tus cargas de trabajo. Desde ahí, puedes navegar a la carga de trabajo de Storage para ver el estado bien arquitecturado o los eventos de todos los sistemas de archivos FSx for ONTAP en tu entorno de almacenamiento.



==== Soporte para la replicación de datos en las instalaciones usando un punto de acceso S3

Workload Factory admite la replicación de datos ONTAP on-premises en la nube para la integración con AWS GenAI, ML y analytics. Puedes replicar tus datos on-premises en un volumen NFS o SMB/CIFS usando un punto de acceso S3.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-replication.html["Replica datos locales usando un punto de acceso S3"]



==== Mejoras del punto de acceso S3 en Storage

Se han realizado varias mejoras en las capacidades de gestión de puntos de acceso S3 en la carga de trabajo de almacenamiento para NetApp Workload Factory. Puedes introducir detalles de configuración de red para tus puntos de acceso S3 y añadir etiquetas de puntos de acceso S3. Las mejoras adicionales incluyen la posibilidad de ver detalles de los buckets S3 y realizar más acciones para gestionar puntos de acceso S3.



===== Detalles del bucket S3 disponibles en Storage

Con los metadatos habilitados para los puntos de acceso de S3, NetApp Workload Factory explora automáticamente tus buckets de AWS S3 y rellena las tablas de S3 para darte una instantánea clara de todos los objetos, sus metadatos, atributos y etiquetas. El acceso a estos detalles te ayuda a mantener el control, la visibilidad y la confianza en los datos de los que eres responsable, mientras reduces la sobrecarga operativa.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/manage-s3-access-points.html["Ver detalles de los puntos de acceso S3 en FSx for ONTAP file systems"]



===== Operaciones de gestión adicionales para puntos de acceso S3

NetApp Workload Factory proporciona operaciones de gestión adicionales para los puntos de acceso S3. Puedes ver los detalles de los puntos de acceso, modificar los puntos de acceso S3 existentes y añadir o eliminar etiquetas de puntos de acceso S3 desde la interfaz de NetApp Workload Factory, agilizando tus tareas de gestión del almacenamiento de objetos.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/manage-s3-access-points.html["Administra los puntos de acceso S3 en NetApp Workload Factory"]



==== Actualizaciones de análisis bien diseñadas

Workload Factory analiza sus sistemas de archivos FSx for ONTAP para las siguientes configuraciones:

* Optimizar el tamaño del volumen de la caché: comprueba si el autodimensionado del volumen y la depuración están activados en los volúmenes de la caché para mantener el tamaño óptimo y centrar la caché en los datos calientes para lograr la máxima eficiencia.
* Dispositivos de bloque inactivos: recomienda archivar los datos de un dispositivo de bloque o eliminar un dispositivo de bloque si no se ha utilizado durante siete días consecutivos.
* Informes lógicos de VM de almacenamiento: verifica si la configuración predeterminada de informes para una VM de almacenamiento está establecida en lógica, lo que proporciona mejor visibilidad del uso del almacenamiento a nivel de volumen.




==== Tarjetas adicionales para dispositivos de bloque

Se han añadido tres nuevas tarjetas a la pestaña Dispositivos de bloque en la carga de trabajo de almacenamiento para proporcionar información rápida sobre el uso y el estado de protección de los dispositivos de bloque:

* Eficiencia de almacenamiento: muestra la capacidad de almacenamiento utilizada y disponible; la capacidad utilizada se desglosa por niveles de almacenamiento SSD y de pool de capacidad.
* Dispositivos protegidos: muestra el porcentaje de dispositivos de bloque con instantáneas, replicación remota, NetApp Autonomous Ransomware Protection (ARP/AI) y copias de seguridad.
* Dispositivos huérfanos: muestra si algún dispositivo de bloque no se ha usado durante siete días seguidos, ayudándote a identificar y gestionar de forma eficaz los recursos que no se están usando. Desde aquí, puedes link:https://docs.netapp.com/us-en/workload-fsx-ontap/manage-block-devices.html#archive-the-data-of-an-inactive-block-device["reclama espacio para dispositivos de bloque no utilizados"].




==== Soporte para la creación y gestión de grupos de iniciadores

NetApp Workload Factory admite crear y gestionar grupos de iniciadores (igroups) para el almacenamiento en bloque en FSx for ONTAP file systems. Los grupos de iniciadores conectan dispositivos de bloque (LUNs) a los recursos de computación que pueden acceder a ellos, proporcionando una capa de permisos para el almacenamiento en bloque en entornos SAN.

* link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-igroup.html["Crea un grupo iniciador en NetApp Workload Factory"]
* link:https://docs.netapp.com/us-en/workload-fsx-ontap/manage-igroups.html["Administra los grupos de iniciadores existentes en NetApp Workload Factory"]




=== Cargas de trabajo de



==== Análisis bien arquitectado para Amazon Elastic VMware Service

Workload Factory ahora ofrece análisis automatizados bien diseñados para tus entornos de Amazon Elastic VMware Service (EVS). Los análisis diarios identifican desajustes de configuración y ofrecen recomendaciones detalladas de corrección para ayudarte a mantener operaciones, seguridad y eficiencia de costos óptimas.

Los análisis se realizan mediante las API de AWS—no se requieren credenciales de vSphere ni conectividad a vCenter. Los resultados están disponibles en la nueva pestaña *Well-architected status* dentro de los detalles de tu entorno EVS.

Esta versión incluye información para:

* *Estado de la protección de parada/terminación de la instancia*: Identifica los nodos EVS sin protección de parada o terminación de EC2. Detener o terminar nodos EVS desde la consola EC2 puede provocar la indisponibilidad de datos de máquinas virtuales o la pérdida de datos.
* *Alineación de la ubicación de la partición del nodo del clúster*: detecta desalineaciones de particiones que podrían provocar una pérdida significativa de potencia de procesamiento o tiempo de inactividad si falla una partición dentro de una AWS Availability Zone. Cada insight incluye niveles de gravedad, hallazgos detallados con información sobre los recursos afectados y procedimientos de remediación paso a paso basados en las mejores prácticas de AWS.


link:view-evs-well-architected.html["Implementa configuraciones bien diseñadas"]



=== Configuración y administración



==== Actualizaciones bien arquitectadas

NetApp Workload Factory incluye la evaluación bien diseñada para cargas de trabajo de Elastic VMware Service (EVS), y añade nuevas configuraciones para cargas de trabajo de Storage y Database.

* *Cargas de trabajo de VMware* NetApp Workload Factory proporciona las mejores prácticas y recomendaciones para operar cargas de trabajo de Amazon Elastic VMware Service (EVS) bien arquitectadas.
+
link:https://docs.netapp.com/us-en/workload-vmware/view-evs-well-architected.html["Implementa configuraciones de EVS bien diseñadas"^]

* *Cargas de trabajo de almacenamiento* Se han añadido varias configuraciones nuevas a la función well-architected en la carga de trabajo de almacenamiento para que tengas más información sobre el rendimiento y los costos del almacenamiento.
+
** Informes lógicos de Storage VM
** Optimiza el tamaño del volumen de caché
** Dispositivos de bloque huérfanos
+
link:https://docs.netapp.com/us-en/workload-fsx-ontap/improve-configurations.html["Implementa configuraciones de sistemas de archivos bien diseñadas para cargas de trabajo de almacenamiento"^]



* *Cargas de trabajo de bases de datos* Workload Factory for Databases incluye una nueva configuración de almacenamiento para Oracle para habilitar y configurar Direct NFS (dNFS) para mejorar el rendimiento de I/O y disminuir la carga en el host y el sistema de almacenamiento.
+
** habilitación de dNFS
** resolución IP coherente de dNFS
** dNFS archivo de configuración
** dNFS `nosharecache`
+
link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["Implementar cargas de trabajo de bases de datos bien diseñadas"^]







==== Nuevos permisos para Storage

Se han añadido nuevos permisos a la carga de trabajo de Storage para mejoras en la gestión de los puntos de acceso S3.

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html#change-log["Registro de cambios de referencia de permisos"]



=== Cargas de trabajo EDA



==== Filtrado mejorado del panel de control con etiquetas personalizables

Ahora puedes configurar hasta cinco filtros personalizados en el panel de EDA según tus etiquetas de AWS. Cada filtro personalizado incluye un nombre de etiqueta, una clave de etiqueta de AWS y un tipo de selección (selección única o múltiple).

La selección múltiple te permite seleccionar varios valores simultáneamente, mientras que la selección única te restringe a un valor a la vez. Los filtros personalizados aparecen en el orden en que los configuras, lo que hace que sea fácil organizar los filtros que usas con más frecuencia.

Si no configuras filtros personalizados, los filtros predeterminados (sistema de archivos, tipo de volumen e intervalo de tiempo) siguen disponibles para que puedas seguir viendo e interactuando con tus cuadros de mando.

https://docs.netapp.com/us-en/workload-eda/task-configure-dashboard.html["Aprende más sobre cómo configurar filtros personalizados"^].



==== Vista de detalles del volumen para un análisis granular del rendimiento

El panel ahora ofrece dos modos de visualización: vista total y vista por volumen. La vista total muestra las métricas agregadas de todos los volúmenes, mientras que la vista por volumen muestra el rendimiento individual de los 10 volúmenes principales a lo largo del tiempo.

En la vista Volumen, las descripciones emergentes interactivas al pasar el cursor ofrecen información detallada para cada volumen, incluyendo el nombre del volumen, las métricas y los valores específicos según el tiempo. Cuando los mismos volúmenes aparecen en varios componentes, un código de colores coherente hace que sea más fácil seguir volúmenes específicos en diferentes métricas.

https://docs.netapp.com/us-en/workload-eda/task-configure-dashboard.html#view-volume-details["Obtén más información sobre cómo ver los detalles del volumen"^].



==== Análisis de latencia para la supervisión proactiva del rendimiento

El análisis de latencia te permite supervisar la latencia de lectura y escritura de volúmenes en tus sistemas de archivos FSx para ONTAP. Puedes configurar umbrales de advertencia y de eventos críticos personalizables para identificar de forma proactiva cuellos de botella en el rendimiento antes de que afecten tus cargas de trabajo EDA.

La tabla de eventos de latencia muestra todos los eventos de advertencia y críticos que te permiten supervisar el rendimiento del volumen e identificar los volúmenes que requieren optimización.

Esta función requiere credenciales de AWS y es accesible desde el menú Latencia en el panel de EDA.

https://docs.netapp.com/us-en/workload-eda/task-monitor-latency.html["Conoce más sobre el análisis de latencia"^].



== 04 de enero de 2026



=== Amazon FSX para ONTAP de NetApp



==== Actualizaciones de análisis bien diseñadas

Workload Factory analiza sus sistemas de archivos FSx for ONTAP para las siguientes configuraciones:

* La protección autónoma contra ransomware de NetApp (ARP/AI) deshabilitada incluye dispositivos de bloque: comprueba si ARP/AI está deshabilitado en los volúmenes de dispositivos de bloque
* Modo de escritura de la relación de caché: verifica si el modo de escritura es óptimo para la carga de trabajo del volumen de caché
* Eliminación de copias de seguridad innecesarias: comprueba si las copias de seguridad están desactualizadas o son innecesarias y se pueden eliminar para reducir costes


link:https://docs.netapp.com/us-en/workload-fsx-ontap/improve-configurations.html["Visualice el estado de buena arquitectura de sus sistemas de archivos FSx para ONTAP"]



==== Integración de la página de inicio del asistente de IA de Ask Me

La página de inicio de la consola Workload Factory incorpora el asistente de IA Ask me, que le permite hacer preguntas sobre su propio almacenamiento, obtener información personalizada directamente de su entorno y consultar conversaciones anteriores. Puede interactuar con Pregúnteme para comprender sus cargas de trabajo, solucionar problemas y obtener más información sobre Workload Factory, todo sin salir de la consola.



==== Uso del principal de usuario de IAM en políticas de permisos basadas en recursos de enlaces Lambda

Los enlaces Lambda que se utilizan para conectar su cuenta de Workload Factory y uno o más sistemas de archivos FSx for ONTAP para realizar operaciones ONTAP avanzadas, ahora usan el principal de usuario de IAM para permisos de políticas basadas en recursos. Este cambio proporciona una mejor alineación con las mejores prácticas de la industria para el acceso a los recursos de AWS.



==== Se agregó una pantalla de análisis para el analizador de IA para eventos EMS

Se ha agregado una nueva pantalla _Análisis_ al menú Almacenamiento. Desde esta pantalla, puede utilizar la función de analizador de IA para eventos EMS de FSx para ONTAP .



==== Mejoras en los dispositivos de bloque en NetApp Workload Factory

Se han realizado las siguientes mejoras para los dispositivos de bloque.



===== Creación de dispositivos de bloque

NetApp Workload Factory admite la creación de dispositivos de bloque mediante el protocolo iSCSI en FSx para sistemas de archivos ONTAP para que pueda brindar un mejor soporte a sus aplicaciones de línea de negocio (LOB) desde la consola de Workload Factory.



===== Mejoras en la gestión de dispositivos de bloque

NetApp Workload Factory incluye las siguientes mejoras para link:https://docs.netapp.com/us-en/workload-fsx-ontap/manage-block-devices.html["gestión de dispositivos de bloque"]. Ahora puede realizar las siguientes tareas desde la consola de Workload Factory:

* Administrar el acceso de los clientes
* Archivar datos del dispositivo de bloque
* Eliminar un dispositivo de bloque




===== Compatibilidad con ARP/AI en volúmenes FlexVol que contienen dispositivos de bloque

Puedes habilitar link:https://docs.netapp.com/us-en/workload-fsx-ontap/ransomware-protection.html["Protección autónoma contra ransomware de NetApp con IA (ARP/AI)"] en volúmenes FlexVol que contienen dispositivos de bloque. La habilitación de ARP/AI detecta ataques de ransomware mediante IA y ayuda en la recuperación de datos.



=== Cargas de trabajo de base de datos



==== Integración de la página de inicio del asistente Ask Me AI

La página de inicio de la consola de Workload Factory incorpora el asistente Ask Me AI, que te permite hacer preguntas sobre tu propio entorno de almacenamiento, obtener información personalizada directamente de tu entorno y consultar conversaciones anteriores. Puedes interactuar con Ask Me para entender tus cargas de trabajo, solucionar problemas y aprender más sobre Workload Factory, todo sin salir de la consola.



=== Cargas de trabajo de



==== Integración de la página de inicio del asistente de IA de Ask Me

La página de inicio de la consola Workload Factory incorpora el asistente de IA Ask me, que le permite hacer preguntas sobre su propio almacenamiento, obtener información personalizada directamente de su entorno y consultar conversaciones anteriores. Puede interactuar con Pregúnteme para comprender sus cargas de trabajo, solucionar problemas y obtener más información sobre Workload Factory, todo sin salir de la consola.



=== Configuración y administración



==== Integración de la página de inicio del asistente de IA de Ask Me

La página de inicio de la consola Workload Factory incorpora el asistente de IA Ask me, que le permite hacer preguntas sobre su propio almacenamiento, obtener información personalizada directamente de su entorno y consultar conversaciones anteriores. Puede interactuar con Pregúnteme para comprender sus cargas de trabajo, solucionar problemas y obtener más información sobre Workload Factory, todo sin salir de la consola.



=== Cargas de trabajo EDA



==== NetApp Workload Factory para desarrolladores ahora NetApp Workload Factory para EDA

Workload Factory para constructores ahora es Workload Factory para EDA. El cambio de nombre refleja el enfoque en las cargas de trabajo de automatización de diseño electrónico (EDA).

Workload Factory para EDA le ayuda a optimizar FSx para ONTAP en múltiples sistemas de archivos. Puede optimizar el rendimiento y reducir los costos operativos automatizando los parámetros de almacenamiento, analizando las restricciones de rendimiento y obteniendo información sobre los proyectos de EDA. Workload Factory para EDA está diseñado para integrarse con sus marcos de infraestructura como código (IaC).



==== Integración de la página de inicio del asistente de IA de Ask Me

La página de inicio de la consola Workload Factory incorpora el asistente de IA Ask me, que le permite hacer preguntas sobre su propio almacenamiento, obtener información personalizada directamente de su entorno y consultar conversaciones anteriores. Puede interactuar con Pregúnteme para comprender sus cargas de trabajo, solucionar problemas y obtener más información sobre Workload Factory, todo sin salir de la consola.



== 18 de diciembre de 2025



=== Cargas de trabajo de base de datos



==== Mejoras en la integración de Active Directory

Workload Factory for Databases incluye tres nuevos campos de Active Directory (AD) al implementar Microsoft SQL Server mediante la opción *Creación avanzada*. Estas mejoras le permiten especificar las preferencias de unión de Active Directory y utilizar una cuenta de servicio administrada.

Los nuevos campos de AD son:

* Controlador de dominio preferido
* Ruta de unidad organizativa preferida
* Grupo de Active Directory de destino


link:https://docs.netapp.com/us-en/workload-databases/create-database.html["Implementar Microsoft SQL Server"]



== 04 de diciembre de 2025



=== Amazon FSX para ONTAP de NetApp



==== Compatibilidad con puntos de acceso AWS S3 para FSx para ONTAP

NetApp Workload Factory admite puntos de acceso AWS S3 para sus sistemas de archivos FSx para ONTAP . Puede crear volúmenes utilizando puntos de acceso S3, asignar puntos de acceso S3 a un volumen existente y administrar puntos de acceso S3 desde la consola de Workload Factory. Al utilizar un punto de acceso S3, puede acceder a los datos de archivos que residen en volúmenes SMB/CIFS o NFS a través de las API de AWS S3. Esto le permite integrar sus datos existentes con GenAI, ML y análisis de los servicios de AWS que admiten puntos de acceso S3.

* link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-volume.html["Crear un volumen utilizando puntos de acceso S3"]
* link:https://docs.netapp.com/us-en/workload-fsx-ontap/manage-s3-access-points.html["Administrar puntos de acceso S3 para un volumen"]

