---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features, administration, amazon fsx for netapp ontap, databases, genai, vmware' 
summary: Obtenga información sobre los cambios más recientes en las cargas de trabajo que forman parte de la fábrica de cargas de trabajo de BlueXP . 
---
= Cambios recientes en el centro de cargas de trabajo de BlueXP
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Obtenga información sobre los cambios más recientes en las cargas de trabajo que forman parte de la fábrica de cargas de trabajo de BlueXP .



== 2025-06-08



=== Amazon FSX para ONTAP de NetApp



==== Nuevo análisis bien diseñado y soporte para solucionar problemas

La gestión automática de la capacidad de los sistemas de archivos FSx para ONTAP ahora se incluye como un análisis de configuración en el panel de estado bien diseñado.

Además, Workload Factory ahora permite solucionar los siguientes problemas de configuración:

* Umbral de capacidad de SSD
* Organización en niveles de los datos
* Snapshots locales programadas
* FSx para copias de seguridad de ONTAP
* Replicación de datos remota
* Eficiencias del almacenamiento
* Gestión de la capacidad automática


link:https://docs.netapp.com/us-en/workload-fsx-ontap/improve-configurations.html["Solucionar problemas de configuración"]



== 2025-06-03



=== Amazon FSX para ONTAP de NetApp



==== Mejora del crecimiento automático del volumen

Ahora puede configurar el tamaño de crecimiento automático de sus volúmenes para que el tamaño del volumen pueda crecer más allá del tamaño previsto para las necesidades comerciales y los requisitos de la aplicación.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/edit-volume-autogrow.html["Habilitar el crecimiento automático del volumen"]



==== Actualización de análisis bien diseñada

Workload Factory ahora analiza sus sistemas de archivos de FSx for ONTAP para comprobar si se están utilizando las eficiencias de almacenamiento, como la compactación, compresión y deduplicación de datos. Las eficiencias de almacenamiento miden la eficacia con la que los sistemas de archivos utilizan el espacio disponible.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/improve-configurations.html["Visualizar el estado bien diseñado de las eficiencias de almacenamiento"]



==== Mejoras en el panel de almacenamiento

A partir de hoy, al abrir la carga de trabajo de almacenamiento desde la consola de la fábrica de cargas de trabajo, verá el *Panel de control*. Este panel, con un nuevo diseño, ofrece una visión integral de sus sistemas FSx for ONTAP, que incluye la cantidad de sistemas de archivos, la capacidad total de SSD, la descripción general del estado de la arquitectura optimizada, la descripción general de la protección de datos y el estado de la relación de replicación.



==== Mejoras en la pestaña Volúmenes

La carga de trabajo de almacenamiento implementó mejoras en la pestaña Volúmenes dentro de un sistema de archivos de FSx for ONTAP en la consola de la fábrica de cargas de trabajo. Las mejoras incluyen:

* *Nuevas tarjetas*: Capacidad SSD, grupo de capacidad y protección autónoma contra ransomware (ARP)
* *Nuevas columnas*: Distribución de capacidad, Capacidad SSD utilizada, Grupo de capacidad utilizada y Eficiencia de SSD




==== Actualización de la eficiencia del almacenamiento para la creación de volúmenes

Al crear un nuevo volumen, las eficiencias de almacenamiento, incluida la compactación, compresión y deduplicación de datos, se habilitan de forma predeterminada.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-volume.html["Crear un nuevo volumen en la fábrica de carga de trabajo"]



=== Cargas de trabajo de base de datos



==== Detección de PostgreSQL y Oracle

Ahora puede descubrir las instancias que ejecutan bases de datos de servidor PostgreSQL e implementaciones de bases de datos Oracle en su cuenta de AWS desde la consola de Workload Factory. Las instancias descubiertas aparecerán en el inventario de bases de datos.



==== Terminología de "Optimización" actualizada

Anteriormente denominada "Optimización", la fábrica de carga de trabajo ahora utiliza "problemas bien diseñados" y "estado bien diseñado" para describir el análisis de las configuraciones de la base de datos y "corrección" para describir la remediación de oportunidades de mejorar las configuraciones de la base de datos para cumplir con las recomendaciones de mejores prácticas.

link:https://docs.netapp.com/us-en/workload-databases/optimize-overview.html["Análisis de configuración para entornos de bases de datos en Workload Factory"]



==== Incorporación mejorada para instancias de host

En lugar de usar los términos "no detectado", "no administrado" o "administrado" para la administración de instancias de host, Workload Factory ahora usa "registrar" para la incorporación de instancias de host. El nuevo proceso de registro incluye la autenticación y preparación de las instancias de host para que pueda crear, supervisar, analizar y corregir recursos en las configuraciones de su base de datos desde la consola de Workload Factory. El paso de preparación del proceso de registro indica si sus instancias de host están listas para la administración.

link:https://docs.netapp.com/us-en/workload-databases/manage-instance.html["Gestión de instancias"]



=== Cargas de trabajo GenAI



==== Rastreador disponible para operaciones de monitoreo y seguimiento

La función de monitoreo de Tracker ya está disponible en GenAI. Puede usar Tracker para monitorear y dar seguimiento al progreso y estado de operaciones pendientes, en curso y completadas, revisar los detalles de las tareas y subtareas de la operación, diagnosticar problemas o fallos, editar parámetros de operaciones fallidas y reintentar operaciones fallidas.

link:https://docs.netapp.com/us-en/workload-genai/general/monitor-operations.html["Supervise las operaciones de carga de trabajo con Tracker en la fábrica de carga de trabajo de BlueXP"]



==== Elija un modelo de reranking para una base de conocimientos

Ahora puede aumentar la relevancia de los resultados de consultas rerankeadas seleccionando un modelo de reranking específico para usar con una base de conocimiento. GenAI es compatible con los modelos Cohere Rerank y Amazon Rerank.

link:https://docs.netapp.com/us-en/workload-genai/knowledge-base/create-knowledgebase.html["Cree una base de conocimientos de GenAI"]



== 2025-05-04



=== Amazon FSX para ONTAP de NetApp



==== Protección autónoma frente a ransomware para sistemas de archivos FSx para ONTAP

Protege tus datos con Autonomous Ransomware Protection (ARP), una función que utiliza análisis de carga de trabajo en entornos NAS (NFS/SMB) para detectar y advertir sobre actividad anormal que podría ser un ataque de ransomware. Cuando se sospecha de un ataque, ARP también crea nuevas instantáneas inmutables desde las que puedes restaurar tus datos.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/ransomware-protection.html["Proteger sus datos con Protección autónoma frente al ransomware"]



==== Mejora del reequilibrio de volúmenes de FlexGroup

La fábrica de cargas de trabajo de BlueXP  presenta el asistente de reequilibrio de volúmenes de FlexGroup con varias opciones de diseño para reequilibrar los datos en un volumen de FlexGroup. El reequilibrio redistribuye los datos de manera uniforme entre los volúmenes miembro de FlexGroup.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/rebalance-volume.html["Reequilibre la capacidad de un volumen FlexGroup"]



==== Implemente las prácticas recomendadas para un sistema de archivos FSx para ONTAP

La fábrica de cargas de trabajo de BlueXP  proporciona un panel donde se puede revisar el estado bien diseñado de las configuraciones del sistema de archivos. Puede aprovechar este análisis para implementar prácticas recomendadas para sus sistemas de archivos FSx para ONTAP. El análisis de configuración del sistema de archivos incluye las siguientes configuraciones: Umbral de capacidad de SSD, snapshots locales programados, backups programados de FSx para ONTAP, organización en niveles de datos y replicación de datos remota.

* link:https://docs.netapp.com/us-en/workload-fsx-ontap/configuration-analysis.html["Obtenga más información sobre el análisis bien diseñado para las configuraciones de sistemas de archivos"]
* link:https://docs.netapp.com/us-en/workload-fsx-ontap/improve-configurations.html["Implemente prácticas recomendadas para sus sistemas de archivos"]




==== Opciones de estilo de seguridad de volúmenes de protocolo doble

Tiene la opción de elegir NTFS o UNIX como estilo de seguridad de un volumen a fin de determinar el método que los usuarios y permisos acceden a un volumen.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-volume.html["Cree un volumen"]



==== Mejoras de replicación



===== Es posible la replicación inversa desde FSx para ONTAP a on-premises

Ahora la replicación inversa está disponible desde un sistema de archivos FSx para ONTAP hasta un clúster ONTAP en las instalaciones desde la consola de fábrica de cargas de trabajo.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/reverse-replication.html["Replicación inversa"]



===== Replicación de volúmenes para la protección de datos

Ahora puede replicar volúmenes de protección de datos.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/cascade-replication.html["Replique un volumen de protección de datos"]



===== Selección de varios volúmenes

Hay disponible una selección de varios volúmenes para que pueda seleccionar exactamente los volúmenes que desea replicar.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-replication.html["Cree una relación de replicación"]



===== Etiquetas de política de retención a largo plazo

Cuando se habilita la retención a largo plazo para una relación de replicación, las etiquetas de los volúmenes de origen y objetivo deben coincidir exactamente. Ahora la fábrica de carga de trabajo BlueXP  puede crear automáticamente etiquetas de volumen de origen que faltan para usted.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-replication.html["Cree una relación de replicación"]



==== Nombre de archivo FSx para ONTAP visible durante la creación de volúmenes

Hemos mejorado la visibilidad de los sistemas de archivos FSx para ONTAP durante la creación de volúmenes. Verá el sistema de archivos FSx para ONTAP cuando cree un volumen de modo que sabrá exactamente dónde se crea el volumen.



==== La cuenta de AWS visible en toda la carga de trabajo de almacenamiento

Hemos mejorado la visibilidad de la cuenta en toda la carga de trabajo de almacenamiento. Verá la cuenta de AWS cuando navegue a las pestañas *Volúmenes*, *VM de almacenamiento* y *Replicación*.



==== Mejoras de asociación de enlaces

* Puedes asociar rápidamente un enlace desde un sistema de archivos FSx para ONTAP en la pestaña Inventario.
* La fábrica de cargas de trabajo de BlueXP  ahora admite el uso de credenciales de usuario de ONTAP alternativas para la asociación de enlaces.




==== Soporte de autenticación de enlaces para AWS Secrets Manager

Ahora tiene la opción de utilizar secretos de AWS Secrets Manager para autenticar enlaces de modo que no tenga que utilizar las credenciales almacenadas en la fábrica de cargas de trabajo de BlueXP .



==== Soporte de respuesta del rastreador

Tracker ahora proporciona respuestas API para que pueda ver la salida de la API de REST en relación con la tarea.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/monitor-operations.html["Supervise las operaciones con Tracker"]



==== Validación de la capacidad en la restauración de un volumen a partir de un backup

Al restaurar un volumen a partir de un backup, la fábrica de cargas de trabajo de BlueXP  determina si existe capacidad suficiente para la restauración y es posible añadir automáticamente la capacidad del nivel de almacenamiento SSD si no lo es.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/restore-from-backup.html["Restaurar un volumen desde un backup"]



==== Compatibilidad con credenciales de usuario de ONTAP alternativas

La fábrica de cargas de trabajo ahora admite conjuntos alternativos de credenciales de ONTAP para crear sistemas de archivos con el fin de minimizar los riesgos de seguridad. En lugar de utilizar solo el usuario fsxadmin, puede seleccionar un conjunto diferente de credenciales de ONTAP o elegir no proporcionar una contraseña para los usuarios fsxadmin y vsaadmin.



==== Terminología de permisos actualizada

La interfaz de usuario y la documentación de la fábrica de carga de trabajo ahora usan "solo lectura" para referirse a los permisos de lectura y "lectura/escritura" para referirse a los permisos de automatización.



=== Cargas de trabajo de base de datos



==== Mejoras en la consola de

* Las vistas entre cuentas y entre regiones están disponibles al navegar entre pestañas de la consola de fábrica de cargas de trabajo de BlueXP . Las nuevas vistas mejoran la gestión, supervisión y optimización de recursos.
* Desde el mosaico *ahorros potenciales* en el panel de control, podrás revisar rápidamente lo que podrías ahorrar cambiando a FSX para ONTAP desde la Tienda de bloques elásticos de Amazon o Amazon FSx para el servidor de archivos de Windows.




==== Exploración ad hoc disponible para configuraciones de base de datos

El centro de cargas de trabajo de BlueXP  para bases de datos analiza automáticamente las instancias gestionadas de Microsoft SQL Server con el almacenamiento FSx para ONTAP para detectar posibles problemas de configuración. Ahora, además de la exploración diaria, puede escanear en cualquier momento.



==== Eliminación de registros de evaluación locales

Después de analizar el ahorro de un host de Microsoft SQL Server en las instalaciones, tiene la opción de eliminar el registro de host en las instalaciones de la fábrica de cargas de trabajo de BlueXP .



==== Mejoras de optimización



===== Limpieza de clones

La evaluación y corrección de limpieza de los clones identifica y gestiona clones antiguos y costosos. Los clones que tengan más de 60 días se pueden actualizar o eliminar de la consola de fábrica de cargas de trabajo de BlueXP .



===== Posponer y descartar el análisis de configuración

Es posible que algunas configuraciones no se apliquen a sus entornos de bases de datos. Ahora dispone de opciones para posponer un análisis de configuración en particular por 30 días o descartar el análisis.



==== Eliminación de registros de evaluación locales

Después de analizar el ahorro de un host de Microsoft SQL Server en las instalaciones, tiene la opción de eliminar el registro de host en las instalaciones de la fábrica de cargas de trabajo de BlueXP .



==== Terminología de permisos actualizada

La interfaz de usuario y la documentación de la fábrica de carga de trabajo ahora usan "solo lectura" para referirse a los permisos de lectura y "lectura/escritura" para referirse a los permisos de automatización.



=== Cargas de trabajo de



==== Mejoras en el asesor de migración de Amazon EC2

Esta versión del centro de cargas de trabajo de BlueXP  para VMware presenta la siguiente mejora en la experiencia del asesor de migración de Amazon EC2:

* Información sobre la infraestructura de datos de NetApp como fuente de datos *: La fábrica de cargas de trabajo ahora se conecta directamente con la información sobre la infraestructura de datos de NetApp para recopilar información sobre la implementación de VMware cuando utiliza el recopilador de datos del asesor de migración EC2.

https://docs.netapp.com/us-en/workload-vmware/launch-onboarding-advisor-native.html["Cree un plan de implementación para Amazon EC2 con el asesor de migración"]



==== Terminología de permisos actualizada

La interfaz de usuario y la documentación de la fábrica de carga de trabajo ahora usan "solo lectura" para referirse a los permisos de lectura y "lectura/escritura" para referirse a los permisos de automatización.



=== Cargas de trabajo GenAI



==== Compatibilidad con NetApp Connector para Amazon Q Business

Esta versión de GenAI presenta compatibilidad con NetApp Connector para Amazon Q Business, lo que le permite crear conectores para Amazon Q Business. Aproveche rápida y fácilmente el asistente de IA de Amazon Q Business con menos configuración inicial que la creación de una base de conocimientos de GenAI para Amazon Bedrock.

link:https://docs.netapp.com/us-en/workload-genai/connector/define-connector.html["Cree un conector de NetApp para Amazon Q Business"]



==== Compatibilidad mejorada con modelos de chat

GenAI ahora admite los siguientes modelos de chat adicionales para las bases de conocimiento:

* link:https://docs.mistral.ai/getting-started/models/models_overview/["Modelos de IA Mistral"^]
* link:https://docs.aws.amazon.com/bedrock/latest/userguide/titan-text-models.html["Modelos de texto de Amazon Titan"^]
* link:https://www.llama.com/docs/model-cards-and-prompt-formats/["Modelos de Meta Llama"^]
* link:https://docs.ai21.com/["Modelos Jamba 1,5"^]
* link:https://docs.cohere.com/docs/the-cohere-platform["Modelos de comando Cohere"^]
* link:https://aws.amazon.com/bedrock/deepseek/["Modelos Deepseek"^]


GenAI admite los modelos de cada proveedor compatible con Amazon Bedrock: link:https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html["Modelos de base admitidos en Amazon Bedrock"^]

link:https://docs.netapp.com/us-en/workload-genai/knowledge-base/create-knowledgebase.html["Cree una base de conocimientos de GenAI"]



==== Terminología de permisos actualizada

La interfaz de usuario y la documentación de la fábrica de carga de trabajo ahora usan "solo lectura" para referirse a los permisos de lectura y "lectura/escritura" para referirse a los permisos de automatización.



=== Configuración y administración



==== Soporte autocompleto de CloudShell

Al utilizar CloudShell de fábrica de carga de trabajo de BlueXP , puede comenzar a escribir un comando y presionar la tecla TAB para ver las opciones disponibles. Si existen múltiples posibilidades, la CLI mostrará una lista de sugerencias. Esta función mejora la productividad al minimizar los errores y acelerar la ejecución de comandos.



==== Terminología de permisos actualizada

La interfaz de usuario y la documentación de la fábrica de carga de trabajo ahora usan "solo lectura" para referirse a los permisos de lectura y "lectura/escritura" para referirse a los permisos de automatización.



== 2025-04-04



=== Cargas de trabajo de base de datos



==== Mejoras de optimización

Hay disponibles nuevas evaluaciones de optimización, soluciones y la visualización de varios recursos al optimizar los entornos de bases de datos.



===== Evaluaciones de resiliencia

Las mejoras incluyen nuevas evaluaciones de resiliencia para comprobar que las funcionalidades de redundancia de datos y recuperación ante desastres estén configuradas para sus entornos de base de datos.

* FSX para backups de ONTAP: Analiza si los sistemas de archivos FSx para ONTAP que sirven los volúmenes de la instancia de SQL Server se configuran con backups programados de FSx para ONTAP.
* Replicación entre regiones: Evalúa si los sistemas de archivos FSx para ONTAP que sirven instancias de Microsoft SQL Server se configuran con una replicación entre regiones.




===== Corrección de computación

La corrección de escala lateral de recepción (RSS) configura RSS para distribuir el procesamiento de red a través de varios procesadores y garantizar una distribución de carga eficiente.



===== Corrección de instantáneas locales

La corrección de snapshots locales configura políticas Snapshot para volúmenes para sus instancias de Microsoft SQL Server con el fin de mantener resilientes los entornos de bases de datos en caso de pérdida de datos.

link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["Optimice las configuraciones"]



===== Soporte para la selección de múltiples recursos

Al optimizar las configuraciones de bases de datos, ahora podrá seleccionar recursos específicos en lugar de todos los recursos.

link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["Optimice las configuraciones"]



==== Vista de inventario mejorada

La pestaña Inventario de la consola de fábrica de cargas de trabajo se ha optimizado para que solo contenga servidores SQL que se ejecutan en Amazon FSx para NetApp ONTAP. Ahora encontrará servidores SQL en las instalaciones y ejecutándose en Amazon Elastic Block Store y Amazon FSx para el servidor de archivos de Windows en la pestaña Explorar ahorros.



==== Creación rápida disponible para la implementación del servidor PostgreSQL

Puede utilizar esta opción de implementación rápida para crear un servidor PostgreSQL con configuración de alta disponibilidad y mejores prácticas integradas.

link:https://docs.netapp.com/us-en/workload-databases/create-postgresql-server.html["Cree un servidor PostgreSQL en la fábrica de cargas de trabajo BlueXP"]



== 2025-03-30



=== Cargas de trabajo de



==== Mejoras en el asesor de migración de Amazon EC2

Esta versión de fábrica de cargas de trabajo de BlueXP  para VMware incluye varias mejoras en la experiencia del asesor de migración de Amazon EC2:

* *Guía mejorada para la asignación de volúmenes*: La información de asignación de volúmenes en los pasos “Clasificar” y “Paquete” del asesor de migración EC2 ofrece una mayor legibilidad y usabilidad. Se muestra información más útil sobre cada volumen, lo que permite identificar mejor los volúmenes y determinar cómo asignarlos.
* * Mejoras de la eficiencia de los scripts de recopilación de datos*: El script recopilador de datos del asesor de migración EC2 optimiza el uso de la CPU al recopilar datos para implementaciones de máquinas virtuales más pequeñas.


https://docs.netapp.com/us-en/workload-vmware/launch-onboarding-advisor-native.html["Cree un plan de implementación para Amazon EC2 con el asesor de migración"]



=== Cargas de trabajo GenAI



==== Compatibilidad con tipos de archivo mejorada

Esta versión de GenAI introduce el soporte de formato de archivo JSON y JSONP al introducir `.json` archivos de orígenes de datos. Se admiten archivos JSON con objetos anidados, con compatibilidad limitada para las cabinas anidadas.

link:https://docs.netapp.com/us-en/workload-genai/knowledge-base/identify-data-sources-knowledge-base.html#supported-data-source-file-formats["Formatos de archivo de origen de datos compatibles"]



==== Soporte de internacionalización para la aplicación de ejemplo de chatbot externa

Ahora puede cambiar fácilmente la interfaz de usuario de la aplicación de chatbot externa de muestra de GenAI a un idioma o configuración regional diferente.

link:https://github.com/NetApp/FSx-ONTAP-samples-scripts/tree/main/AI/GenAI-ChatBot-application-sample#netapp-workload-factory-genai-sample-application["Aplicación de chatbot de muestra externa de GenAI"]



==== Soporte para el modelo de chat Anthropic Claude Sonnet 3,7

GenAI ahora incluye soporte para el modelo de chat Anthropic Claude 3,7 Sonnet. Las características beta de Claude 3,7 Sonnet permiten hasta 128K tokens de salida por solicitud y admiten nuevas acciones de uso de computadoras. El modo de pensamiento extendido de Claude 3,7 Sonnet será compatible en un futuro lanzamiento de GenAI.

link:https://docs.netapp.com/us-en/workload-genai/knowledge-base/create-knowledgebase.html["Cree una base de conocimientos de GenAI"]



==== Compatibilidad con la adición de orígenes de datos desde recursos compartidos genéricos de NFS/SMB

Con la API de fábrica de cargas de trabajo, ahora puede agregar un origen de datos desde un recurso compartido genérico de NFSv3, NFSv4 o SMB. Cuando añades un origen de datos desde un recurso compartido NFS o SMB, el volumen de base de conocimientos permanece en un volumen de Amazon FSx para NetApp ONTAP. La interfaz de usuario web de fábrica de cargas de trabajo admitirá esta función en una versión futura.

link:https://console.workloads.netapp.com/api-doc["Utilice la API de fábrica de cargas de trabajo"^]



==== Compatibilidad con iguales de VPC

Ahora puede implementar la infraestructura de GenAI en link:https://docs.aws.amazon.com/vpc/latest/peering/what-is-vpc-peering.html["Clouds privados virtuales (VPC) con conexión entre iguales"^]la misma región y usar la misma cuenta de AWS. Puede implementar el motor de IA en una VPC y, a continuación, crear una base de conocimientos en una VPC entre iguales y seleccionar sistemas de archivos de Amazon FSx for NetApp ONTAP que residan en una VPC entre iguales.

link:https://docs.netapp.com/us-en/workload-genai/knowledge-base/create-knowledgebase.html["Cree una base de conocimientos de GenAI"]



=== Configuración y administración



==== CloudShell informa de respuestas de errores generadas por IA para comandos de la CLI de ONTAP

Al usar CloudShell, cada vez que emita un comando de la CLI de ONTAP y se produce un error, puede obtener respuestas de error generadas por IA que incluyen una descripción del fallo, la causa del fallo y una resolución detallada.

link:https://docs.netapp.com/us-en/workload-setup-admin/use-cloudshell.html["Usar CloudShell"]



==== iam:SimulatePermissionPolicy actualización de permisos

Ahora puede administrar `iam:SimulatePrincipalPolicy` el permiso desde la consola de fábrica de cargas de trabajo cuando agrega credenciales de cuenta de AWS adicionales o agrega una nueva capacidad de carga de trabajo, como la carga de trabajo de GenAI.

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html#change-log["Log de cambios de referencia de permisos"]



== 2025-03-02



=== Cargas de trabajo de



==== Mejoras en el asesor de migración de Amazon EC2

Esta versión de fábrica de cargas de trabajo de BlueXP  para VMware incluye varias mejoras en la experiencia del asesor de migración de Amazon EC2:

* *Tipo de instancia estimado*: El asesor de migración ahora puede examinar los requisitos de su entorno y proporcionar un tipo de instancia estimado de Amazon EC2 para cada VM. Puede optar por incluir el tipo de instancia estimado para cada máquina virtual durante el paso de alcance del asesor de migración.
* *Posibilidad de recomendar volúmenes de Amazon EBS*: El asesor de migración ahora puede recomendar migrar volúmenes de datos a Amazon Elastic Block Store (EBS) en lugar de Amazon FSx para NetApp ONTAP debido a las necesidades específicas de capacidad o rendimiento de una determinada región.
* *Asignación automática del sistema de archivos mejorada*: La asignación del sistema de archivos de Amazon FSx para NetApp ONTAP se ha mejorado para optimizar mejor el costo y minimizar el rendimiento.


https://docs.netapp.com/us-en/workload-vmware/launch-onboarding-advisor-native.html["Cree un plan de implementación para Amazon EC2 con el asesor de migración"]



== 2 de febrero de 2025



=== Configuración y administración



==== CloudShell disponible en la consola de fábrica de cargas de trabajo de BlueXP

CloudShell está disponible desde cualquier lugar de la consola de fábrica de cargas de trabajo de BlueXP . CloudShell le permite usar las credenciales de AWS y ONTAP que ha proporcionado en su cuenta de BlueXP  y ejecutar comandos de la CLI de AWS o comandos de la CLI de ONTAP en un entorno similar al shell.

link:https://docs.netapp.com/us-en/workload-setup-admin/use-cloudshell.html["Usar CloudShell"]



==== Actualización de permisos para bases de datos

El siguiente permiso ahora está disponible en el modo _READ_ para bases de datos `iam:SimulatePrincipalPolicy`: .

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html#change-log["Log de cambios de referencia de permisos"]
