= 4 de agosto de 2024
:allow-uri-read: 




== 4 de agosto de 2024

Directiva no resuelta en <stdin> - Include::_include/workload-fsx-ONTAP.adoc[] :leveloffset: +1



=== Soporte de terraform

Ahora puede utilizar Terraform de CodeBox para implementar y gestionar sistemas de archivos y equipos virtuales de almacenamiento.

* link:create-file-system.html["Crear un sistema de archivos"]
* link:create-storage-vm.html["Cree una máquina virtual de almacenamiento"]
* link:https://docs.netapp.com/us-en/workload-setup-admin/use-codebox.html["Utilice Terraform de CodeBox"^]




=== Recomendaciones de rendimiento y IOPS en la calculadora de almacenamiento

La calculadora de almacenamiento hace recomendaciones para la configuración del sistema de archivos FSx para ONTAP para el rendimiento e IOPS basadas en las prácticas recomendadas de AWS, lo que proporciona una orientación óptima para sus selecciones.



== 7 de julio de 2024

Directiva no resuelta en <stdin> - Include::_include/workload-fsx-ONTAP.adoc[] :leveloffset: +1



=== Lanzamiento inicial de Workload Factory para Amazon FSx para NetApp ONTAP

Amazon FSx para NetApp ONTAP está disponible de forma general en Workload Factory.
