= Optimice de forma continua sus cargas de trabajo de Microsoft SQL Server con bases de datos
:allow-uri-read: 




=== Optimice de forma continua sus cargas de trabajo de Microsoft SQL Server con bases de datos

La fábrica de cargas de trabajo de BlueXP  presenta directrices y barreras continuas para garantizar una optimización continua y el cumplimiento de las prácticas recomendadas para el componente de almacenamiento de tus cargas de trabajo de Microsoft SQL Server en Amazon FSx para NetApp ONTAP. Esta función analiza continuamente su estado de Microsoft SQL Server sin conexión, lo que le proporciona un informe completo de información, oportunidades y recomendaciones para ayudarle a lograr el máximo rendimiento, rentabilidad y cumplimiento.

link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["Optimice sus cargas de trabajo de SQL Server"]



=== Soporte de terraform

Ahora puede utilizar Terraform desde CodeBox para implementar Microsoft SQL Server.

* link:https://docs.netapp.com/us-en/workload-databases/create-database-server.html["Cree un servidor de base de datos"^]
* link:https://docs.netapp.com/us-en/workload-setup-admin/use-codebox.html["Utilice Terraform de CodeBox"^]

