= Mejoras en la calculadora de ahorro
:allow-uri-read: 




=== Mejoras en la calculadora de ahorro

* Descripciones de estimación de costes
+
Ahora puedes descubrir cómo se calculan las estimaciones de costes en la calculadora de ahorro. Podrás revisar las descripciones de todos los cálculos de tus instancias de Microsoft SQL Server con el almacenamiento Amazon Elastic Block Store en comparación con el uso de Amazon FSx para el almacenamiento de ONTAP.

* Soporte para el grupo de disponibilidad siempre disponible
+
Ahora las bases de datos proporcionan cálculos de ahorro de costes para el tipo de implementación de grupos de disponibilidad Always On con Microsoft SQL Server mediante Amazon Elastic Block Store.

* Optimiza las licencias de SQL Server con FSx para ONTAP
+
La calculadora de bases de datos determina si la edición de licencia de SQL que utiliza con el almacenamiento de Amazon Elastic Block Store está optimizada para las cargas de trabajo de base de datos. Obtendrás una recomendación sobre la licencia SQL óptima con el almacenamiento FSx para ONTAP.

* Varias instancias de SQL Server
+
Ahora las bases de datos proporcionan cálculos de ahorro de costes para una configuración que aloja varias instancias de Microsoft SQL Server mediante Amazon Elastic Block Store.

* Personalizar la configuración de la calculadora
+
Ahora puede personalizar la configuración de Microsoft SQL Server, Amazon EC2 y Elastic Block Store para explorar los ahorros manualmente. La calculadora de ahorro determinará la mejor configuración en función del coste.



link:explore-savings.html["Explora el ahorro con FSx para ONTAP para tus cargas de trabajo de base de datos."]
