= La optimización continua añade soluciones de computación y evaluación
:allow-uri-read: 




=== La optimización continua añade soluciones de computación y evaluación

Las bases de datos ahora ofrecen información y recomendaciones para ayudarle a optimizar los recursos de computación para instancias de Microsoft SQL Server. Medimos el uso de la CPU y aprovechamos el servicio AWS Compute Optimizer para recomendar tipos de instancia óptimos de tamaño adecuado y notificarle los parches disponibles del sistema operativo. La optimización de los recursos de computación puede ayudarle a tomar decisiones fundamentadas sobre los tipos de instancias, lo que lleva a ahorrar costes y a lograr una utilización eficiente de los recursos.

link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["Optimiza las configuraciones de recursos de computación"]



=== Soporte PostgreSQL

Ahora puede implementar y administrar implementaciones de servidores PostgreSQL independientes en bases de datos.

link:https://docs.netapp.com/us-en/workload-databases/create-postgresql-server.html["Crear un servidor PostgreSQL"]
