= Compatibilidad con modo lectura para la gestión del almacenamiento
:allow-uri-read: 




=== Compatibilidad con modo lectura para la gestión del almacenamiento

El modo de lectura está disponible para la gestión del almacenamiento en la fábrica de cargas de trabajo. El modo de lectura mejora la experiencia del modo básico al agregar permisos de solo lectura para que las plantillas de infraestructura como código se rellenen con sus variables específicas. Las plantillas de infraestructura como código se pueden ejecutar directamente desde la cuenta de AWS sin necesidad de proporcionar permisos de modificación a la fábrica de cargas de trabajo.

link:https://docs.netapp.com/us-en/workload-setup-admin/operational-modes.html["Más información sobre el modo de lectura"]



=== Realice backups antes de la eliminación de volúmenes

Ahora puede realizar un backup de un volumen antes de eliminarlo. La copia de seguridad permanecerá en el sistema de archivos hasta que se elimine.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/delete-volume.html["Eliminar un volumen"]
