= Compatibilidad con el servicio de notificación de fábrica de carga de trabajo de BlueXP
:allow-uri-read: 




=== Compatibilidad con el servicio de notificación de fábrica de carga de trabajo de BlueXP

El servicio de notificaciones de la fábrica de cargas de trabajo de BlueXP permite que esta envíe notificaciones al servicio de alertas de BlueXP o a un tema de Amazon SNS. Las notificaciones enviadas a las alertas de BlueXP aparecen en el panel de alertas de BlueXP. Cuando la fábrica de cargas de trabajo publica notificaciones en un tema de Amazon SNS, los suscriptores del tema (como usuarios u otras aplicaciones) reciben las notificaciones en los endpoints configurados para el tema (como correos electrónicos o mensajes SMS).

link:https://docs.netapp.com/us-en/workload-setup-admin/configure-notifications.html["Configurar las notificaciones de fábrica de la carga de trabajo de BlueXP"^]

La fábrica de carga de trabajo proporciona las siguientes notificaciones para las bases de datos:

* Informe bien diseñado
* Implementación del host
* Protección




=== Mejora de incorporación para el registro de instancias

Workload Factory para bases de datos ha mejorado su proceso de incorporación para registrar instancias que se ejecutan en Amazon FSx para almacenamiento de NetApp ONTAP. Ahora puede seleccionar instancias en bloque para su registro. Una vez registrada una instancia, puede crear y administrar recursos de host de base de datos desde la consola de Workload Factory.

link:https://docs.netapp.com/us-en/workload-databases/manage-instance.html["Gestión de instancias"]



=== Análisis y corrección del tiempo de espera de E/S de múltiples rutas de Microsoft

El estado de buena arquitectura para las instancias del host de base de datos ahora incluye el análisis y la corrección del tiempo de espera de E/S multiruta de Microsoft (MPIO). Establecer el tiempo de espera de MPIO en 60 segundos garantiza la conectividad y la estabilidad del almacenamiento de FSx for ONTAP durante las conmutaciones por error. Si la configuración de MPIO no se configura correctamente, Workload Factory proporcionará una corrección para establecer el tiempo de espera de MPIO en 60 segundos.

link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["Implementar configuraciones de base de datos bien diseñadas en la fábrica de carga de trabajo"]



=== Mejoras en los gráficos del inventario del host

Desde la pantalla de inventario del host, varios gráficos de utilización de recursos, como el rendimiento y las IOPS, ahora muestran datos de 7 días para que pueda supervisar el rendimiento de los nodos SQL desde la consola de Workload Factory de forma más eficiente. Las métricas de rendimiento recopiladas de los nodos SQL se guardarán en Amazon CloudWatch, que puede utilizarse para Logs Insights o para la integración con otros servicios de análisis de su entorno.

Desde las pestañas Instancias y Bases de datos dentro del inventario del host, hemos mejorado la descripción y la visualización para la protección del host.



=== Compatibilidad con la autenticación de Windows en la fábrica de carga de trabajo

Ahora, la fábrica de carga de trabajo admite la autenticación de SQL Server mediante usuarios autenticados de Windows para registrar instancias de host y beneficiarse de las funciones de administración de host.

link:https://docs.netapp.com/us-en/workload-databases/register-instance.html["Registrar instancias de host en la fábrica de carga de trabajo para bases de datos"]
