= Detección de PostgreSQL y Oracle
:allow-uri-read: 




=== Detección de PostgreSQL y Oracle

Ahora puede descubrir las instancias que ejecutan bases de datos de servidor PostgreSQL e implementaciones de bases de datos Oracle en su cuenta de AWS desde la consola de Workload Factory. Las instancias descubiertas aparecerán en el inventario de bases de datos.



=== Terminología de "Optimización" actualizada

Anteriormente denominada "Optimización", la fábrica de carga de trabajo ahora utiliza "problemas bien diseñados" y "estado bien diseñado" para describir el análisis de las configuraciones de la base de datos y "corrección" para describir la remediación de oportunidades de mejorar las configuraciones de la base de datos para cumplir con las recomendaciones de mejores prácticas.

link:https://docs.netapp.com/us-en/workload-databases/optimize-overview.html["Análisis de configuración para entornos de bases de datos en Workload Factory"]



=== Incorporación mejorada para instancias de host

En lugar de usar los términos "no detectado", "no administrado" o "administrado" para la administración de instancias de host, Workload Factory ahora usa "registrar" para la incorporación de instancias de host. El nuevo proceso de registro incluye la autenticación y preparación de las instancias de host para que pueda crear, supervisar, analizar y corregir recursos en las configuraciones de su base de datos desde la consola de Workload Factory. El paso de preparación del proceso de registro indica si sus instancias de host están listas para la administración.

link:https://docs.netapp.com/us-en/workload-databases/manage-instance.html["Gestión de instancias"]
