= BlueXP workload factory ahora Fábrica de cargas de trabajo de NetApp
:allow-uri-read: 




=== BlueXP workload factory ahora Fábrica de cargas de trabajo de NetApp

BlueXP ha sido renombrado y rediseñado para reflejar mejor el papel que desempeña en la gestión de su infraestructura de datos. Como resultado, la BlueXP workload factory pasó a llamarse Fábrica de carga de trabajo de NetApp .



=== Mejoras para Oracle en la consola de Workload Factory



==== Pantalla de recursos de la base de datos Oracle

Cada base de datos de Oracle tiene su propia pantalla de recursos dedicada disponible en el inventario de bases de datos. La pantalla de recursos proporciona una descripción general del nombre de la base de datos, el estado (en línea o fuera de línea), la tenencia y el tipo de implementación. También se incluyen gráficos con los siguientes datos durante un período de tres meses: utilización de CPU, latencia, IOPS y rendimiento. La utilización de la capacidad proporciona el tamaño total de la base de datos, el tamaño de los datos escritos, la capacidad de la unidad de estado sólido utilizada y la capacidad de almacenamiento utilizada.

Desde la pantalla de recursos, puede ver información sobre el servidor Oracle (modelo de implementación, sistema operativo, edición, versión y más), ubicación (cuenta de AWS, región, zona de disponibilidad y subred), almacenamiento y procesamiento (detalles del sistema de archivos FSx para ONTAP , tipo de instancia de base de datos y LUN y volúmenes asociados) y conectividad (VPC y protocolo de acceso). También puede comprobar el estado de la arquitectura de las configuraciones de la base de datos y ver las bases de datos conectables (PDB) asociadas con la base de datos.



==== Compatibilidad con bases de datos conectables de Oracle

Las bases de datos conectables de Oracle se pueden ver en el inventario de bases de datos y desde la pantalla de recursos de su base de datos contenedora principal. La siguiente información sobre sus PDB está disponible: nombre de CDB, nombre de host, estado de protección, tamaño de la base de datos, sistema de archivos FSx para ONTAP , credenciales de AWS, cuenta de AWS y región.



==== Análisis bien diseñado para Oracle

El análisis bien diseñado incluye evaluaciones de problemas de configuración con el diseño de almacenamiento para bases de datos Oracle sobre NFS o sobre iSCSI con o sin Administración automática de almacenamiento (ASM) y problemas de configuración de almacenamiento en el sistema operativo para Oracle sobre LUN iSCSI. Puede utilizar esta información para tomar decisiones informadas sobre las implementaciones de sus bases de datos y garantizar que funcionen de manera eficiente.

link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["Implementar configuraciones de base de datos bien diseñadas en Workload Factory"]



=== Mejoras en el inventario de bases de datos

Desde la pantalla de instancia en el inventario de bases de datos, las opciones para corregir, posponer y descartar un problema de configuración están disponibles para instancias individuales o múltiples de Microsoft SQL Server o para bases de datos individuales o múltiples de Oracle.



=== Optimizar el ahorro en función del uso de Amazon Elastic Block Store (EBS)

Workload Factory puede analizar el uso del rendimiento de EBS y luego sugerir la mejor y más rentable configuración de FSx para ONTAP para que pueda ahorrar más al cambiar a FSx para ONTAP.

link:https://docs.netapp.com/us-en/workload-databases/explore-savings.html#explore-savings-for-detected-hosts["Explore los ahorros para los entornos de almacenamiento detectados en la consola de Workload Factory"]
