= Compatibilidad con los modelos de base de Amazon Nova
:allow-uri-read: 




=== Compatibilidad con los modelos de base de Amazon Nova

GenAI ahora es compatible con los modelos básicos de Amazon Nova. Amazon Nova Micro, Amazon Nova Lite y Amazon Nova Pro son compatibles.

link:https://docs.netapp.com/us-en/workload-genai/requirements.html["Requisitos de GenAI"]



=== Filtrado de tipo de archivo para orígenes de datos

GenAI ahora admite la selección de tipos de archivo específicos para incluir en el análisis de origen de datos al agregar un origen de datos.

link:https://docs.netapp.com/us-en/workload-genai/create-knowledgebase.html#add-data-sources-to-the-knowledge-base["Agregue orígenes de datos a la base de conocimientos"]



=== Filtrado de fecha de modificación de archivo para orígenes de datos

GenAI ahora admite el filtrado de archivos para incluirlos en el análisis de origen de datos por fecha de modificación al agregar un origen de datos. Puede elegir un rango de fechas de modificación para los archivos incluidos.

link:https://docs.netapp.com/us-en/workload-genai/create-knowledgebase.html#add-data-sources-to-the-knowledge-base["Agregue orígenes de datos a la base de conocimientos"]



=== Soporte para archivos de imagen y soporte mejorado para archivos PDF

GenAI ahora admite la mejora de las respuestas a las consultas de la base de conocimientos con información de las imágenes y descripciones de gráficos, así como el texto de los documentos, lo que conduce a respuestas más ricas y de mayor calidad. GenAI ahora puede escanear archivos de imagen e imágenes dentro de archivos PDF (también conocido como soporte de archivos multimodal). Si decide digitalizar imágenes o archivos PDF, el texto de las imágenes (incluidas las imágenes incrustadas en documentos PDF) se escanea en la fuente de datos y las perspectivas de los escaneos se incluyen en las respuestas a las consultas de la base de conocimientos.

link:https://docs.netapp.com/us-en/workload-genai/create-knowledgebase.html#add-data-sources-to-the-knowledge-base["Agregue orígenes de datos a la base de conocimientos"]



=== Soporte híbrido de búsqueda y reselección

Ahora GenAI puede mejorar significativamente la relevancia y precisión de los resultados de búsqueda mediante la búsqueda híbrida y la re-clasificación de los resultados. La búsqueda híbrida combina los puntos fuertes de la búsqueda tradicional basada en palabras clave con técnicas avanzadas de búsqueda semántica densas basadas en vectores. Los resultados de búsqueda de palabras clave estándar se aumentan con coincidencias cercanas y matices lingüísticos, lo que mejora la relevancia. Luego, GenAI refina aún más estos resultados mediante el uso de modelos avanzados de re-clasificación, como Cohere Rerank y Amazon Rerank, y devuelve los resultados más relevantes. Esta capacidad está disponible para las bases de conocimiento recién creadas.

link:https://docs.netapp.com/us-en/workload-genai/ai-workloads-overview.html#benefits-of-using-genai-to-create-generative-ai-applications["Obtén más información sobre el centro de cargas de trabajo de BlueXP  para GenAI"]
