= Los entornos de bases de datos on-premises analizan los costes y planifican las migraciones
:allow-uri-read: 




=== Los entornos de bases de datos on-premises analizan los costes y planifican las migraciones

La fábrica de cargas de trabajo de BlueXP  para bases de datos ahora detecta, analiza y ayuda a planificar la migración de bases de datos on-premises a Amazon FSx para NetApp ONTAP. Puedes utilizar la calculadora de ahorro para estimar el coste que supone ejecutar tu entorno de bases de datos on-premises en la nube y revisar las recomendaciones para migrar tu entorno de bases de datos on-premises a la nube.

link:https://docs.netapp.com/us-en/workload-databases/explore-savings.html["Explora el ahorro que puedes conseguir en entornos de bases de datos on-premises"]



=== Nuevas evaluaciones de optimización para bases de datos

Las siguientes evaluaciones ahora están disponibles en el fábrica de cargas de trabajo BlueXP  para bases de datos. Estas evaluaciones se centran en detectar y proteger contra posibles vulnerabilidades de seguridad, y en detectar y aliviar los cuellos de botella en el rendimiento.

* *Configuración de la escala lateral de recepción (RSS)*: Comprueba si la configuración RSS está habilitada y si el número de colas está establecido en el valor recomendado. La evaluación también proporciona recomendaciones para optimizar la configuración RSS.
* *Configuración del servidor de grado máximo de paralelismo (MAXDOP)*: La evaluación comprueba si MAXDOP está configurado correctamente y proporciona recomendaciones para optimizar el rendimiento.
* *Parches de Microsoft SQL Server*: La evaluación comprueba si los parches más recientes están instalados en las instancias de SQL Server y proporciona recomendaciones para instalar los parches más recientes.


link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["Optimice las configuraciones"]
