= Explorador de volúmenes
:allow-uri-read: 




[[volumes-explorer]]
=== Explorador de volúmenes

Volumes Explorer te ofrece una vista sencilla y con función de búsqueda de todos tus volúmenes en NetApp Workload Factory. Comprueba rápidamente qué volúmenes dan servicio a cargas de trabajo de bloques o de archivos. Consulta el tamaño lógico de cada volumen, la capacidad física utilizada y si utiliza funciones de eficiencia de almacenamiento (compresión, deduplicación y compactación). Filtra y ordena por nombre, estado (disponible/fallido), latencia, tamaño, capacidad utilizada y funciones de protección.



[[enhanced-email-notifications-for-replication-delays]]
=== Notificaciones por correo electrónico mejoradas sobre retrasos en la replicación

Las notificaciones por correo electrónico sobre retrasos en la replicación incluyen ahora más detalles sobre la relación afectada. La notificación te ayuda a identificar rápidamente la relación afectada y a analizarla en la consola de NetApp Workload Factory.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/track-replication-delays.html["Activar las notificaciones sobre retrasos en la replicación"]



[[block-device-creation-enhancement]]
=== Mejora en la creación de dispositivos de bloque

Workload Factory permite crear dispositivos de bloque a partir de una instantánea de volumen.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-block-device.html["Crear un dispositivo de bloque a partir de una instantánea de volumen en Workload Factory"]
