= Ya está disponible un nuevo panel bien diseñado para todos los sistemas FSx for ONTAP
:allow-uri-read: 




=== Ya está disponible un nuevo panel bien diseñado para todos los sistemas FSx for ONTAP

El análisis well-architected ya está disponible para los sistemas de archivos FSx for ONTAP desde el nuevo panel well-architected en NetApp Workload Factory. El nuevo panel ofrece una vista centralizada de todos tus sistemas de archivos en todas las cuentas y regiones y sus configuraciones en un solo lugar. Aparece una notificación emergente cuando visitas la pestaña *Well-architected* desde un sistema de archivos. Accede al nuevo panel seleccionando *Well-architected* en el menú de navegación de la izquierda en Workload Factory.

Aún puedes acceder al análisis de *Well-architected* para un sistema de archivos concreto y desde la opción de menú *Well-architected* en Storage.



=== Nuevas recomendaciones en el análisis bien arquitectado

Workload Factory ahora incluye las siguientes configuraciones en el análisis bien arquitectado para los sistemas de archivos FSx for ONTAP:

* Conectar el host al nodo de conmutación por error: comprueba si los hosts están conectados al nodo de conmutación por error en un sistema de archivos FSx para ONTAP de tipo activo-pasivo y sugiere conectar los hosts al nodo de conmutación por error para garantizar la fiabilidad.
* Conectar el host al nodo preferido: comprueba si los hosts están conectados a sus dispositivos de bloque usando el nodo preferido y sugiere conectar los hosts al nodo preferido para eficiencia en el rendimiento.




=== Explorador de volúmenes

Volumes Explorer te ofrece una vista sencilla y con función de búsqueda de todos tus volúmenes en NetApp Workload Factory. Comprueba rápidamente qué volúmenes dan servicio a cargas de trabajo de bloques o de archivos. Consulta el tamaño lógico de cada volumen, la capacidad física utilizada y si utiliza funciones de eficiencia de almacenamiento (compresión, deduplicación y compactación). Filtra y ordena por nombre, estado (disponible/fallido), latencia, tamaño, capacidad utilizada y funciones de protección.



=== Mejoras en el retraso de replicación



==== Notificaciones por correo electrónico mejoradas sobre retrasos en la replicación

Las notificaciones por correo electrónico sobre retrasos en la replicación incluyen ahora más detalles sobre la relación afectada. La notificación te ayuda a identificar rápidamente la relación afectada y a analizarla en la consola de NetApp Workload Factory.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/track-replication-delays.html["Activar las notificaciones sobre retrasos en la replicación"]



==== Exportar los datos de retraso de replicación a CSV

Ahora puedes exportar los datos sobre el retraso en la replicación a un archivo CSV para analizarlos en una hoja de cálculo y compartirlos con otras personas.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/track-replication-delays.html["Haz un seguimiento de los retrasos en la replicación"]



=== Mejora en la creación de dispositivos de bloque

Workload Factory permite crear dispositivos de bloque a partir de una instantánea de volumen.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-block-device.html["Crear un dispositivo de bloque a partir de una instantánea de volumen en Workload Factory"]
